<a href="https://colab.research.google.com/github/Nick97382000/Lettura_bilanci/blob/main/Lettura%20bilanci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lettura bilanci

Installo librerie di interesse e copio directory di riferimento da Git-Hub

In [23]:
!git clone https://github.com/Nick97382000/Lettura_bilanci

import sys
sys.path.insert(0, '/content/Lettura_bilanci')

!git -C /content/Lettura_bilanci pull   # aggiorna i file

import importlib, dependencies
importlib.reload(dependencies)

fatal: destination path 'Lettura_bilanci' already exists and is not an empty directory.
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 2.92 KiB | 427.00 KiB/s, done.
From https://github.com/Nick97382000/Lettura_bilanci
   32a9707..6704600  main       -> origin/main
Updating 32a9707..6704600
Fast-forward
 Lettura bilanci.ipynb | 240 ++++++++++++++++----------------------------------
 summary.py            |  54 ++++++++++++
 2 files changed, 129 insertions(+), 165 deletions(-)
Installing Python package: pillow...
Updating apt-get...
Installing apt packages: tesseract-ocr, tesseract-ocr-ita, poppler-utils...

In [24]:
import funzioni_base, funz_sec_liv, config as cf, ocr_func as ocr, summary
importlib.reload(funzioni_base)
importlib.reload(funz_sec_liv)
importlib.reload(cf)
importlib.reload(ocr)
importlib.reload(summary)

Leggo tutti i pdf nella cartella e stampo la tabella di sintesi

In [25]:
import glob
import os
import pandas as pd
from summary import summary_tabella, trova_tabella_bilancio

pdf_files = glob.glob("Lettura_bilanci/deposito bilanci/*.pdf")

summary = {}

for pdf_path in pdf_files:
    nome = os.path.basename(pdf_path).replace(".pdf", "")
    tabella = trova_tabella_bilancio(pdf_path, cf.keywords_first_page)

    if tabella is not None:
        summary[nome] = summary_tabella(tabella, cf.campi_bilancio)



# stampa i risultati ottenuti
for nome, df in summary.items():
    print("\n" + "=" * 80)
    print(f"BILANCIO: {nome}")
    print("=" * 80)
    print(df)

================================================================================
BILANCIO: Volpato Industrie - Consolidato - 2024
================================================================================
                                           31-12-2024   31-12-2023
totale_attivo                              97737768.0  105606567.0
patrimonio_netto                           41957742.0   40978696.0
totale_attivo_circolante                   55074605.0   61397489.0
Totale_disponibilità_liquide               14156221.0   23944466.0
Totale_debiti                              50496961.0   59894867.0
Totale_rimanenze                           16435894.0   13791909.0
Totale_crediti_verso_clienti               19000152.0   17710304.0
Totale_debiti_verso_fornitori              16483302.0   15871700.0
Totale_debiti_verso_banche                 30375818.0   39636260.0
avviamento                                 16644208.0   16568852.0
ricavi_vendite_e_prestazioni               87375547.0   70278325.0
Utile_perdita_esercizio                     3956168.0    4658191.0
Risultato_prima_delle_imposte               6160080.0    5985159.0
Totale_ammortamenti_e_svalutazioni          7525685.0    3712005.0
Totale_interessi_e_altri_oneri              1937857.0     687591.0
immobilizzazioni_immateriali               21393216.0   21290799.0
immobilizzazioni_materiali                 20605919.0   22398574.0
immobilizzazioni_finanziarie                 315805.0     131297.0
Flusso_finanziario_attivita_operativa       7190156.0   13656402.0
Flusso_finanziario_attività_investimento   -4358662.0  -35166655.0
Flusso_finanziario_attività_finanziamento -12619739.0   22859992.0
passivita_correnti                         27107631.0   32483091.0

================================================================================
BILANCIO: Volpato Industrie - Civilistico - 2024
================================================================================
                                           31-12-2024  31-12-2023
totale_attivo                              77215809.0  77158352.0
patrimonio_netto                           39001550.0  39296076.0
totale_attivo_circolante                   39785638.0  39139925.0
Totale_disponibilità_liquide                7885152.0  10417013.0
Totale_debiti                              36110055.0  36177382.0
Totale_rimanenze                           12434595.0  10231994.0
Totale_crediti_verso_clienti               14796439.0  13346082.0
Totale_debiti_verso_fornitori              12968817.0  11927095.0
Totale_debiti_verso_banche                 20429454.0  21238037.0
avviamento                                        NaN         NaN
ricavi_vendite_e_prestazioni               62224926.0  65517637.0
Utile_perdita_esercizio                     2695780.0   4381058.0
Risultato_prima_delle_imposte               3481842.0   5593496.0
Totale_ammortamenti_e_svalutazioni          3704196.0   3409007.0
Totale_interessi_e_altri_oneri              1244562.0    587710.0
immobilizzazioni_immateriali                4286506.0   4444433.0
immobilizzazioni_materiali                 12439994.0  12961203.0
immobilizzazioni_finanziarie               20432472.0  20227472.0
Flusso_finanziario_attivita_operativa       2874764.0  14245584.0
Flusso_finanziario_attività_investimento   -1598042.0 -21943501.0
Flusso_finanziario_attività_finanziamento  -3808583.0   8552373.0
passivita_correnti                         20485031.0  18699960.0

================================================================================
BILANCIO: Gollinucci - 2024
================================================================================
                                           31-12-2024  31-12-2023
totale_attivo                              34087270.0  22766880.0
patrimonio_netto                           19350241.0  15153957.0
totale_attivo_circolante                   11717234.0  18259510.0
Totale_disponibilità_liquide                4709597.0  11981963.0
Totale_debiti                              13232032.0   6810402.0
Totale_rimanenze                            3079966.0   2829415.0
Totale_crediti_verso_clienti                2624411.0   3145372.0
Totale_debiti_verso_fornitori               2655387.0   3077701.0
Totale_debiti_verso_banche                  9579023.0   2871256.0
avviamento                                 16032816.0         0.0
ricavi_vendite_e_prestazioni               19674840.0  20055260.0
Utile_perdita_esercizio                      642760.0   2172984.0
Risultato_prima_delle_imposte               1648222.0   2840912.0
Totale_ammortamenti_e_svalutazioni          3462194.0   1130789.0
Totale_interessi_e_altri_oneri               665562.0     67413.0
immobilizzazioni_immateriali               16482492.0    249078.0
immobilizzazioni_materiali                  5539194.0   4119034.0
immobilizzazioni_finanziarie                 274706.0    124998.0
Flusso_finanziario_attivita_operativa       4400980.0   4903833.0
Flusso_finanziario_attività_investimento   -3381112.0   -863905.0
Flusso_finanziario_attività_finanziamento  -8292233.0  -1223658.0
passivita_correnti                          5652328.0   5153976.0

================================================================================
BILANCIO: Conserve Italia - Civilistico e Consolidato - 2024
================================================================================
                                           30 giugno 2025  30 giugno 2024
totale_attivo                                 932834011.0     879915161.0
patrimonio_netto                              305929558.0     300611685.0
totale_attivo_circolante                      439099320.0     416207934.0
Totale_disponibilità_liquide                  127609819.0     106847278.0
Totale_debiti                                 591475140.0     545013151.0
Totale_rimanenze                              205612371.0     201996264.0
Totale_crediti_verso_clienti                   55501954.0      60932295.0
Totale_debiti_verso_fornitori                 236897353.0     228044458.0
Totale_debiti_verso_banche                    191590518.0     168282068.0
avviamento                                            NaN             NaN
ricavi_vendite_e_prestazioni                  709159879.0     733550069.0
Utile_perdita_esercizio                         4787472.0       9540622.0
Risultato_prima_delle_imposte                   4806517.0       9561256.0
Totale_ammortamenti_e_svalutazioni            -31210733.0     -30398405.0
Totale_interessi_e_altri_oneri                -18826861.0     -21543220.0
immobilizzazioni_immateriali                   44577002.0      47325342.0
immobilizzazioni_materiali                    342717358.0     306685238.0
immobilizzazioni_finanziarie                  103068871.0     106983634.0
Flusso_finanziario_attivita_operativa          50640501.0      47095488.0
Flusso_finanziario_attività_investimento      -60736793.0     -35519602.0
Flusso_finanziario_attività_finanziamento      30858833.0     -20625683.0
passivita_correnti                            197257981.0     186885089.0

================================================================================
BILANCIO: Valtellina - 2024
================================================================================
                                            31-12-2024   31-12-2023
totale_attivo                              250006305.0  229638858.0
patrimonio_netto                            61305455.0   56175195.0
totale_attivo_circolante                   187543091.0  185084246.0
Totale_disponibilità_liquide                10973940.0   16503906.0
Totale_debiti                              162338791.0  147569430.0
Totale_rimanenze                           110566346.0   91968335.0
Totale_crediti_verso_clienti                45713002.0   50821290.0
Totale_debiti_verso_fornitori               93300761.0   94223386.0
Totale_debiti_verso_banche                  40085441.0   24659657.0
avviamento                                     20000.0      87000.0
ricavi_vendite_e_prestazioni               290308450.0  280124262.0
Utile_perdita_esercizio                      5103126.0    4215880.0
Risultato_prima_delle_imposte                8922840.0    8670937.0
Totale_ammortamenti_e_svalutazioni           5581586.0    5672180.0
Totale_interessi_e_altri_oneri               4020825.0    2437762.0
immobilizzazioni_immateriali                 3481091.0    3879906.0
immobilizzazioni_materiali                  20852418.0   22781852.0
immobilizzazioni_finanziarie                29891247.0    9937530.0
Flusso_finanziario_attivita_operativa       -4341595.0  -24278522.0
Flusso_finanziario_attività_investimento     4751855.0      52017.0
Flusso_finanziario_attività_finanziamento   11025784.0    5075094.0
passivita_correnti                         137451509.0  125718620.0

================================================================================
BILANCIO: IFB SRL - 2024
================================================================================
                                           31-12-2024  31-12-2023
totale_attivo                              19224599.0  16661921.0
patrimonio_netto                           10269303.0   7759354.0
totale_attivo_circolante                    3380961.0   2680962.0
Totale_disponibilità_liquide                1047175.0    335010.0
Totale_debiti                               8675095.0   8622366.0
Totale_rimanenze                            2292149.0   2292149.0
Totale_crediti_verso_clienti                      NaN         NaN
Totale_debiti_verso_fornitori                     NaN         NaN
Totale_debiti_verso_banche                        NaN         NaN
avviamento                                        NaN         NaN
ricavi_vendite_e_prestazioni                  20094.0     19634.0
Utile_perdita_esercizio                     2509948.0    -56242.0
Risultato_prima_delle_imposte               2539818.0    -62796.0
Totale_ammortamenti_e_svalutazioni             3999.0       178.0
Totale_interessi_e_altri_oneri                31290.0     10828.0
immobilizzazioni_immateriali                      0.0         0.0
immobilizzazioni_materiali                    31819.0       899.0
immobilizzazioni_finanziarie               15791331.0  13963949.0
Flusso_finanziario_attivita_operativa             NaN         NaN
Flusso_finanziario_attività_investimento          NaN         NaN
Flusso_finanziario_attività_finanziamento         NaN         NaN
passivita_correnti                           218070.0     15663.0

Debug

In [26]:

pdf_path= "Lettura_bilanci/deposito bilanci/Conserve Italia - Civilistico e Consolidato - 2024.pdf"
#pdf_path= "Lettura_bilanci/deposito bilanci/Gollinucci - 2024.pdf"
tabella = trova_tabella_bilancio(pdf_path, cf.keywords_first_page)
summary_tabella(tabella, cf.campi_bilancio)

                                           30 giugno 2025  30 giugno 2024
totale_attivo                                 932834011.0     879915161.0
patrimonio_netto                              305929558.0     300611685.0
totale_attivo_circolante                      439099320.0     416207934.0
Totale_disponibilità_liquide                  127609819.0     106847278.0
Totale_debiti                                 591475140.0     545013151.0
Totale_rimanenze                              205612371.0     201996264.0
Totale_crediti_verso_clienti                   55501954.0      60932295.0
Totale_debiti_verso_fornitori                 236897353.0     228044458.0
Totale_debiti_verso_banche                    191590518.0     168282068.0
avviamento                                            NaN             NaN
ricavi_vendite_e_prestazioni                  709159879.0     733550069.0
Utile_perdita_esercizio                         4787472.0       9540622.0
Risultato_prima_delle_imposte                   4806517.0       9561256.0
Totale_ammortamenti_e_svalutazioni            -31210733.0     -30398405.0
Totale_interessi_e_altri_oneri                -18826861.0     -21543220.0
immobilizzazioni_immateriali                   44577002.0      47325342.0
immobilizzazioni_materiali                    342717358.0     306685238.0
immobilizzazioni_finanziarie                  103068871.0     106983634.0
Flusso_finanziario_attivita_operativa          50640501.0      47095488.0
Flusso_finanziario_attività_investimento      -60736793.0     -35519602.0
Flusso_finanziario_attività_finanziamento      30858833.0     -20625683.0
passivita_correnti                            197257981.0     186885089.0

In [27]:
df = ocr.trova_tabella_oic_multipaagina(
    pdf_path="Lettura_bilanci/deposito bilanci/Kirey - 2024.pdf",
    start_marker="stato patrimoniale",
    end_marker="conto economico",
    lang="ita",
    dpi=300
)

df.head(50)
df.tail(50)

,label,data1,data2
76,Varie altre riserve,51,(2.879)
77,Totale altre riserve,64.138.921,17.230.521
78,VII Riserva per operazioni di copertura dei fl...,(381.859),381.860
79,-,None,None
80,VIII Utili (perdite) portati a nuovo,(16.360),(871.643)
81,-,None,None
82,IX Utile (perdita) dell'esercizio,(8.901.374),1.648.856
83,-,None,None
84,X Riserva negativa per azioni proprie in porta...,0,0
85,-,None,None
86,Totale patrimonio netto,62.228.948,41.049.020
87,B) Fondi per rischi e oneri,None,None
88,1) per trattamento di quiescenza e obblighi si...,0,0
89,"2) per imposte, anche differite",212.489,445.601
90,3) strumenti finanziari derivati passivi,0,0
91,4) altri,0,0
92,Totale fondi per rischi ed oneri,212.489,445.601
93,C) Trattamento di fine rapporto di lavoro subo...,1.196.626,1.244.209
94,D) Debiti,None,None
95,3) debiti verso soci per finanziamenti,None,None
96,esigibili entro l'esercizio successivo,None,None
97,esigibili oltre l'esercizio successivo,None,500.000
98,Totale debiti verso soci per finanziamenti,None,500.000
99,4) debiti verso banche,None,None
100,esigibili entro l'esercizio successivo,2.019.579,9.750.180
101,esigibili oltre l'esercizio successivo,30.236.628,9.534.855
102,Totale debiti verso banche,32.256.207,19.285.035
103,7) debiti verso fornitori,None,None
104,esigibili entro l'esercizio successivo,17.582.236,13.091.650
105,esigibili oltre l'esercizio successivo,0,None
106,Totale debiti verso fornitori,17.582.236,13.091.650
107,9) debiti verso imprese controllate,None,None
108,esigibili entro l'esercizio successivo,31.242.436,23.926.533
109,esigibili oltre l'esercizio successivo,0,None
110,6 di.,73,None
111,-,None,None
112,Totale debiti tributari,2.166.148,2.137.913
113,13) debiti verso istituti di previdenza e di s...,None,None
114,esigibili entro l'esercizio successivo,1.208.756,1.110.525
115,esigibili oltre l'esercizio successivo,0,None
116,Totale debiti verso istituti di previdenza e d...,1.208.756,1.110.525
117,14) altri debiti,None,None
118,esigibili entro l'esercizio successivo,3.489.687,3.741.890
119,esigibili oltre l'esercizio successivo,0,3.044.565
120,Totale altri debiti,3.489.687,6.786.455
121,Totale debiti,87.945.470,66.838.111
122,E) Ratei e risconti,8.575.634,8.422.301
123,Totale passivo,160.159.167,117.999.242
124,7 di.,73,None
125,-,None,None

In [28]:
print(df)

                                                 label        data1  \
0                                               Attivo         None
1    A) Crediti verso soci per versamenti ancora do...         None
2    Totale crediti verso soci per versamenti ancor...         None
3                                  B) Immobilizzazioni         None
4                       | Immobilizzazioni immateriali         None
..                                                 ...          ...
121                                      Totale debiti   87.945.470
122                                E) Ratei e risconti    8.575.634
123                                     Totale passivo  160.159.167
124                                              7 di.           73
125                                                  -         None

           data2
0           None
1           None
2           None
3           None
4           None
..           ...
121   66.838.111
122    8.422.301
123  117.999.242
124         None
125         None

[126 rows x 3 columns]